### ISSUE TITLE
Error Message 

### ISSUE THREAD

**Issue by Sdoof** [Sebastiaan76/truefx-downloader#2]
Hello - thanks for putting this package together. Sadly being a newbie and trying to learn I am facing some difficulties, (below is the error). I understand that I should export the Go Daddy certificate (as an ASCII), which is what I did but I don't know what to do with that file - e.g how do I install it on my system?

`Traceback (most recent call last):
  File "/home/olivier/PycharmProjects/IB/venv/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 441, in wrap_socket
    cnx.do_handshake()
  File "/home/olivier/PycharmProjects/IB/venv/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1806, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/home/olivier/PycharmProjects/IB/venv/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1546, in _raise_ssl_error
    _raise_current_error()
  File "/home/olivier/PycharmProjects/IB/venv/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/olivier/PycharmProjects/IB/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/olivier/PycharmProjects/IB/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/home/olivier/PycharmProjects/IB/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/home/olivier/PycharmProjects/IB/venv/lib/python3.6/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/home/olivier/PycharmProjects/IB/venv/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/olivier/PycharmProjects/IB/venv/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 448, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/olivier/PycharmProjects/IB/venv/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/olivier/PycharmProjects/IB/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/olivier/PycharmProjects/IB/venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.truefx.com', port=443): Max retries exceeded with url: /?page=loginz (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "download.py", line 98, in <module>
    main()
  File "download.py", line 81, in main
    find_files(sys.argv[1], sys.argv[2], path)
  File "download.py", line 55, in find_files
    session.post('https://www.truefx.com/?page=loginz', data=payload)
  File "/home/olivier/PycharmProjects/IB/venv/lib/python3.6/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/olivier/PycharmProjects/IB/venv/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/olivier/PycharmProjects/IB/venv/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/olivier/PycharmProjects/IB/venv/lib/python3.6/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.truefx.com', port=443): Max retries exceeded with url: /?page=loginz (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
`

**Comment by Sebastiaan76** [comment]
Hey there, 
Sorry for the late reply. That error is definitely to do with not having the GoDaddy certificate correctly installed on your system.

Without knowing what system ( Windows, Linux - if so, which distro etc ) it's not really possible to help - other than to say you would have 2 options.

1. Change the url to http instead of https ( and send your password for truefx in the clear - no big deal if you use a 'disposable' password ).
2. Figure out how to install the certificate at the system level.

I was getting the same errors until I got the cert installed correctly.

Hope that helps.

**Comment by Sdoof** [comment]
Thanks Sebastiaan, I am on Windows 10. How do I insure that the GoDaddy certificate is correctly installed?

**Comment by Sebastiaan76** [comment]
Hi Sdoof, I'm not overly familiar with Windows10 ( I'm a Linux user ), but you could try the guide outlined here: https://windowsreport.com/install-windows-10-root-certificates/ 

Alternatively, if that doesn't work. I'd edit the code and make it http, instead of https. Just make sure you have a password that you don't really care about, i.e. signup to Truefx with a "disposable" account.

Hope you get it working!

**Comment by Sdoof** [comment]
Thanks for the prompt reply Sebastiaan - that really helps!

**Comment by Sebastiaan76** [comment]
Hey there,
I've done a major re-write of this tool ( and some related ones ). Let me know how you go with this newer version.
